Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: helloworld.handler.App
      CodeUri: D:\Mayank\Agent On-Boarding Solution\backend\AgentRegistration\HelloWorldFunction
      Runtime: java8