package helloworld.config;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerator;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.security.SecureRandom;
import java.util.UUID;

@DynamoDBAutoGenerated(generator=CustomGeneratedKey.Generator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface CustomGeneratedKey {
  String prefix() default "";

  public static class Generator implements DynamoDBAutoGenerator<String> {
    private final String prefix;
    static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    static SecureRandom rnd = new SecureRandom();

    public String randomString(int len) {
      StringBuilder sb = new StringBuilder(len);
      for(int i=0; i<len; i++)
        sb.append(AB.charAt(rnd.nextInt(AB.length())));
      return sb.toString();
    }
    public Generator(final Class<String> targetType, final CustomGeneratedKey annotation) {
      this.prefix = annotation.prefix();
    }
    public Generator() { //<- required if annotating directly
      this.prefix = "";
    }
    @Override
    public DynamoDBAutoGenerateStrategy getGenerateStrategy() {
      return DynamoDBAutoGenerateStrategy.CREATE;
    }
    @Override
    public final String generate(final String currentValue) {
      return prefix + randomString(5);
    }
  }
}